name: Daily Security Scan

permissions:
  # Required to upload SARIF file to CodeQL. See: https://github.com/github/codeql-action/issues/2117
  actions: read
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Only need to read contents
  contents: read
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Run OSV Scanner
        uses: google/osv-scanner-action@v2.0.2
        with:
          scan-args: |-
            --format sarif 
            --output results.sarif 
            ./app/
    
      - name: Upload SARIF report to Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
