name: Daily Security Scan

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action

      - name: Add step to send report to security dashboard
        uses: github/codeql-action/upload-sarif
